"""create lists, todo_items, blacklisted_sites tables, users

Revision ID: 90da6140f6ca
Revises: 
Create Date: 2017-09-05 15:34:58.275076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90da6140f6ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False, unique=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False, unique=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blacklisted_site_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('blacklisted_site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blacklisted_site_id'], ['blacklisted_sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_items')
    op.drop_table('lists')
    op.drop_table('blacklisted_site_users')
    op.drop_table('users')
    op.drop_table('blacklisted_sites')
    # ### end Alembic commands ###
